### ISSUE TITLE
[Calculation Module] Failure on multiple selection tool with rasterstats function from multiply_raster.py file

### ISSUE THREAD

**Issue by neodark** [enermaps/enermaps#110]
### Summary

The calculation module `multiply raster` fails when two polygons are selected. 

### Steps to reproduce

Enable `selection` and the tiff `overlay`, then draw two polygons around some overlay colors and then click on `Multiply raster`

### What is the current bug behavior?

It returns an error message on the **frontend**:

```
status
FAILURE
results: "'dict' object has no attribute 'startswith'"
```

and the following error message in the **backend**:

```
cm-multiply_1  | [2020-12-03 22:12:40,120: ERROR/ForkPoolWorker-4] Task __main__.multiply_raster[0dad13f9-1dda-49c2-80af-80b9063ad527] raised unexpected: AttributeError("'dict' object has no attribute 'startswith'")
cm-multiply_1  | Traceback (most recent call last):
cm-multiply_1  |   File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 409, in trace_task
cm-multiply_1  |     R = retval = fun(*args, **kwargs)
cm-multiply_1  |   File "worker.py", line 70, in multiply_raster
cm-multiply_1  |     val_multiply = rasterstats(selection, raster_path, factor)
cm-multiply_1  |   File "/cm-multiply/multiply_raster.py", line 54, in rasterstats
cm-multiply_1  |     stats = zonal_stats(
cm-multiply_1  |   File "/usr/local/lib/python3.8/dist-packages/rasterstats/main.py", line 31, in zonal_stats
cm-multiply_1  |     return list(gen_zonal_stats(*args, **kwargs))
cm-multiply_1  |   File "/usr/local/lib/python3.8/dist-packages/rasterstats/main.py", line 125, in gen_zonal_stats
cm-multiply_1  |     stats, run_count = check_stats(stats, categorical)
cm-multiply_1  |   File "/usr/local/lib/python3.8/dist-packages/rasterstats/utils.py", line 91, in check_stats
cm-multiply_1  |     if x.startswith("percentile_"):
cm-multiply_1  | AttributeError: 'dict' object has no attribute 'startswith'
```
### What is the expected correct behavior?

We should get no error message on the backend and a normal calculation output on the frontend:
```
task_id
bcf3a...
status
SUCCESS
results: [{"min":2,"max":80,"mean":42.689655172413794,"count":29,"median":45}]
```

### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/2482166/101095450-3ab60d80-35be-11eb-83da-258336a04b72.png)

### Possible fixes

The error comes from the name `stats` used multiple times at wrong places:
 
```
        stats = zonal_stats(
            projected_shape, raster_path, affine=src.transform, stats=stats
        )
        # we have a single feature, thus we expose a single stat
        aggregated_stats += stats
    scale_stat(aggregated_stats, factor)
```
One hotfix to this is to replace with the following:
```
        one_stat = zonal_stats(
            projected_shape, raster_path, affine=src.transform, stats=stats
        )
        # we have a single feature, thus we expose a single stat
        aggregated_stats += one_stat
    scale_stat(aggregated_stats, factor)
```
This helps correct the failure but I am not sure this is the expected output with having a list of two values rather than a real aggregation as shown by this image:

![image](https://user-images.githubusercontent.com/2482166/101096316-b3699980-35bf-11eb-8e9c-4627320ff29d.png)

On a side note:
the function `rasterstats` is only used by the worker `multiply_raster` that does not define `stats` parameter and when looking at the test, I am not sure there's a test for `rasterstats` that verifies what happens with that parameter and that function in general.

**Comment by gcmalloc** [comment]
In the linked PR, added a unittest for the multiple feature in a featureset.
Fix the underlying issue.
