### ISSUE TITLE
Renaming Docker Containers to enermaps instead of enermaps2

### ISSUE THREAD

**Issue by knackbord** [enermaps/enermaps#118]

**Comment by gcmalloc** [comment]
You can rename the directory name into anything you want, the docker-compose stack will adjust its name to that directory.
The repository name was recently changed from enermaps/enermaps2 to enermaps/enermaps, so the remote need to be changed accordingly with `git remote set-url origin git@github.com:enermaps/enermaps.git`.

Is there another issue you encountered ?

**Comment by knackbord** [comment]
nope, thanks for the hint
