### ISSUE TITLE
CM is overlaying the selection

### ISSUE THREAD

**Issue by knackbord** [enermaps/enermaps#152]
![image](https://user-images.githubusercontent.com/1956145/103815526-c4487780-5063-11eb-8e8a-d84cfe84410e.png)

I can not close the CM.

**Comment by gcmalloc** [comment]
Pretty annoying one.

**Comment by gcmalloc** [comment]
Is the size of your screen bigger than the selection tool + calculation module output ?

**Comment by gcmalloc** [comment]
Here the question is where should those control be ? I think it would be nice to just have the possibility to close that pane.
