### ISSUE TITLE
README.md missing information for some paragraphs

### ISSUE THREAD

**Issue by neodark** [enermaps/enermaps#17]
Could you please update the second part of the `README.md` file with `frontend`,  `api`, `db`.

I guess you were talking about the `development` purpose without using `docker-compose`. Is this correct?

In that case, it would be better to give full instructions such as:

- create the virtual environment
- pip install those requirements
- on a terminal launch the flask server
- on another terminal ...
- etc.

**Comment by gcmalloc** [comment]
The current workflow for developpement is only around docker-compose. It doesn't support live reload yet so rebuilding the docker image is required. The main problem is that you need to have mapnik installed on your computer to get the tile rendering running correctly, it can take a pretty long time to setup, thus the advised use of docker-compose for developpement purpose.

I lightened up the README and removed the additional section to reflect this #18, take a look.

**Comment by gcmalloc** [comment]
Closing this, reopen if you think it is still relevant.
