### ISSUE TITLE
Resolve the bug in the CM broker where the queue crashed if more than one CM is launched.

### ISSUE THREAD

**Issue by dianevg** [enermaps/enermaps#216]
Option 1 : Enregistrer tous les workers sur toutes les tâches (fichiers de configuration).

Option 2: Créer toutes les tâches à la volée (tout ré-implémenter) -> 1 mois de travail.

todo: contacter Malik (informel)+ ouvrir issue.

**Comment by neodark** [comment]
Will close this one as it's a duplicate of https://github.com/enermaps/enermaps/issues/219 which explains the problem in a better way
