### ISSUE TITLE
Datasets metadata thourgh the postgrest API

### ISSUE THREAD

**Issue by melhk** [enermaps/enermaps#258]
I am trying to get the datasets metadata through the API like this:
```
    url = DATASETS_SERVER_URL + "rpc/enermaps_get_metadata"
    try:
        with requests.post(
            url,
            headers={"Authorization": "Bearer {}".format(DATASETS_SERVER_API_KEY)}
        ) as resp:
            resp_data = resp.json()
    except ConnectionError:
        raise
```
with the server url `DATASETS_SERVER_URL = "https://lab.idiap.ch/enermaps/api/"`

but I get the errror :
```
{'hint': 'No function matches the given name and argument types. You might need to add explicit type casts.', 'details': None, 'code': '42883', 'message': 'function public.enermaps_get_metadata() does not exist'}
```

And I can not find any documentation about this function. What I am missing?

**Comment by gperonato** [comment]
The `enermaps_get_metadata(shared_id text)` function is meant to be used by the OpenAIRE gateway (the `shared_id` is needed then).
There is currently no function to retrieve only the specific metadata needed by the frontend, as initially I thought the frontend was going to be using directly sql queries instead of PostgREST.
This query mentioned in the doc to retrieve in the metadata
```sql
SELECT (metadata ->> 'variables')::jsonb as variables,
		TO_TIMESTAMP(metadata ->> 'start_at', 'YYYY-MM-DD HH24:MI')::timestamp without time zone as start_at,
		TO_TIMESTAMP(metadata ->> 'end_at', 'YYYY-MM-DD HH24:MI')::timestamp without time zone as end_at,
        (metadata ->> 'parameters')::jsonb as parameters,
        (metadata ->> 'is_raster')::bool as is_raster,
        metadata ->> 'temporal_granularity' as temporal_granularity,
        (metadata ->> 'custom_periods')::jsonb as custom_periods,
        (metadata ->> 'is_tiled')::bool as is_tiled,
        (metadata ->> 'levels')::jsonb as levels,
        (metadata ->>' to_be_fixed')::bool as to_be_fixed from datasets;
```
could be transformed into a sql view and then should be accessible via PostGREST.

**Comment by melhk** [comment]
Yes, we are trying to use the DB directly to see if we can save some time, but since it was a backup solution I thought that the API was already usable I continued to work with it. 

This function should be accessible through the API, otherwise how can a user know the parameters to pass to the function `get_enermaps_geojson` ?

**Comment by gperonato** [comment]
I have created a `paramaters`view, which is now available here:
https://lab.idiap.ch/enermaps/api/parameters

**Comment by melhk** [comment]
Thank you.
In fact I was trying to get the datasets ids and "human readable names", and I thought that they would be return by the function "get_metadata".
How can I get them?

**Comment by gperonato** [comment]
What is missing in the above endpoint?

**Comment by melhk** [comment]
I don't understand where is the "human readable name" = the name that the dataset should have in the interface, and the id of the dataset?

**Comment by gperonato** [comment]
I have updated the view. It now provides the `ds_id` and the `title` of the dataset

**Comment by melhk** [comment]
Thank you!

**Comment by melhk** [comment]
This is not working, I have tried with the address `DATASETS_SERVER_URL = "https://lab.idiap.ch/enermaps/api/rpc/parameters"` and `DATASETS_SERVER_URL = "https://lab.idiap.ch/enermaps/api/parameters"` .

I get the error 
```
{'hint': 'No function matches the given name and argument types. You might need to add explicit type casts.', 'details': None, 'code': '42883', 'message': 'function public.parameters() does not exist'}
```
for the first one and 
```
{'message': 'Error in $: not enough input'}
```
for the second one

**Comment by gperonato** [comment]
It is a GET endpoint, not a POST.
It is also accessible via a web browser.

**Comment by melhk** [comment]
Ok it is working now, with the address `"https://lab.idiap.ch/enermaps/api/parameters"`
