### ISSUE TITLE
NUTS and LAU files seem incomplete

### ISSUE THREAD

**Issue by melhk** [enermaps/enermaps#259]
We are trying to display NUTS and LAU files. Unfortunately the data does not seem complete.

For example, the "country" level is missing Portugal and Italy (among others) and the "LAU" level is only displayed for Albania and a small region of Austria. Here are 2 snapshots from a geojson viewer.

![country](https://user-images.githubusercontent.com/11057275/126347418-56445c39-c3be-4177-9bf0-691f4f433b0c.PNG)

![lau](https://user-images.githubusercontent.com/11057275/126347441-7adbb05d-e7b5-4645-9175-191a2b5acd9c.PNG)

**Comment by gperonato** [comment]
Which row limit are you using? -------- Messaggio originale --------Da: Mélanie Huck ***@***.***>Data: mar 20 lug 2021, 17:03A: enermaps/enermaps ***@***.***>Cc: Giuseppe Peronato ***@***.***>, Assign ***@***.***>Oggetto: [enermaps/enermaps] NUTS and LAU files seem incomplete (#259)
We are trying to display NUTS and LAU files. Unfortunately the data does not seem complete.
For example, the "country" level is missing Portugal and Italy (among others) and the "LAU" level is only displayed for Albania and a small region of Austria. Here are 2 snapshots from a geojson viewer.

**Comment by melhk** [comment]
I did not specify a row limit, I thought I would get the whole file with the parameters you indicated to me. What row limit should I put to get the entire files?

**Comment by gperonato** [comment]
I don't remember exactly, there are about 200 countries and 2-3k LAU. Just use 10000 to be sure. -------- Messaggio originale --------Da: Mélanie Huck ***@***.***>Data: mar 20 lug 2021, 17:25A: enermaps/enermaps ***@***.***>Cc: Giuseppe Peronato ***@***.***>, Assign ***@***.***>Oggetto: Re: [enermaps/enermaps] NUTS and LAU files seem incomplete (#259)
I did not specify a row limit, I thought I would get the whole file with the parameters you indicated to me. What row limit should I put to get the entire files?

**Comment by melhk** [comment]
Thanks.
I have tried to put 10000, but it looked like it was not enough, so I put 100000. How can I be sure that I get the whole layer?

**Comment by gperonato** [comment]
Sorry I meant NUTS in the previous message. There are actually about 100k LAU.
More precisely:
- 257 `country`
- 125 `NUTS1`
- 334 `NUTS2`
- 1514 `NUTS3`
- 99207 `LAU`

So depending on your specific need you can use these figures above, or just a `102000` limit.

There is no implemented method to retrieve the number of features, apart from querying the database directly,
for instance:
`SELECT COUNT(fid) from spatial where levl_code = ANY('{LAU}'::levl[]);`

The suggested 10k limit in the doc was meant for *normal* datasets, not NUTS/LAU.

**Comment by melhk** [comment]
Ok thank you.
This is something important that we should be able to know in the backend without hard coding it for the future use of the database, but we can leave it like that for the September demonstration.

**Comment by Kanma** [comment]
Not an issue in the current version of the web app.
