### ISSUE TITLE
Large raster files should not have to be downloaded as multiple files.

### ISSUE THREAD

**Issue by melhk** [enermaps/enermaps#263]
The backend can not handle the reconstruction of the original file from multiple files, but we need the original file.

**Comment by gperonato** [comment]
The original file is too large to be handled (several GBs). Do you have any alternative methods?

**Comment by melhk** [comment]
Sorry, I have no alternative method and the backend can't handle that job. So I guess these rasters will be abandonned.

**Comment by Kanma** [comment]
Not an issue anymore in the current version of the web app.
