### ISSUE TITLE
Legends for raster files

### ISSUE THREAD

**Issue by melhk** [enermaps/enermaps#268]
@dianevg @gperonato How do we get legends for raster files, if there are any?

**Comment by gperonato** [comment]
The raster files do not contain a specific color scale. The legend and associated color scale should be created by the front-end. I think there is something that might be reused from Hotmaps.

**Comment by melhk** [comment]
In Hotmaps, the legends are an image file like this one:

![geoserver-GetLegendGraphic image](https://user-images.githubusercontent.com/11057275/128671049-ee602d00-7743-43dc-a0f5-8a07d4d21d00.png)

that the frontend gets by calling the geoserver for example at the address `https://geoserver.hotmaps.eu/geoserver/hotmaps/wms?REQUEST=GetLegendGraphic&amp;VERSION=1.0.0&amp;FORMAT=image/png&amp;WIDTH=50&amp;HEIGHT=10&amp;STRICT=false&amp;style=heat`.

This is not something that we can compute in the frontend.

**Comment by dianevg** [comment]
Hello eveybody, how are you?

In this issues, are we talking about finding a color scale for the raster ? Because I think that we have discussed that at the last meeting: We would use a "default" colormap based on the maximum and minimum values. It is true that we have concentrated more on the vector files in the last meeting, but the principle should be the same for the raster for me. 

Or are we talking about having an image which shows the colormap in the front-end? For this, I don't know, I think that it should be added to the front-end using existing library, but I let you choose what you think adequate here.

**Comment by melhk** [comment]
Hello @dianevg 

We are talking about having all the data we need to deduce which color indicates what and to display this information in the front end.

For vector files, we were able to manually select which variable we were interested in, find its minimum and maximum value, then store this information in the configuration file. This was rather easy to do because it is easy to read a json file and I was able to find all the information in this file.

The configuration file stores all the information that the database should normally send back to us and if we need any of these information we call a function that fetch the information from the configuration file instead of the database. 

This works for the September demo, and we could implement something similar for raster files, keeping in mind that this is only a temporary fix and not something that will be expandable down the road. 

But, even to implement this temporary solution, we are missing some information. I can manually open a raster file, and, using some library, read the color map. This gives me a list of colors present in the image.

We still need to know:
- Where can we read what variable contains the image, what is the type of the variable (numeric, categorical)?
- Which value corresponds to which color in the color table (color list), and where can we read them?
- Which are the minimum and maximum values present in the image, were can we find them (if the image represents numeric variables)?
- What are the units of the variable, if any? Where can we read this information?
- Should we cut the values into different intervals? For example, an image display only 3 different zones with 3 different colors (categorical variable), we would need a legend for each color. But if an image represents linear information with a lot of colors (it can go up to 256), we can not display each color in the front end legend and we would like to display a caption giving information for color intervals. 

Maybe you could give us a concrete example using a raster from the database and showing us how to find all the previous information? Thanks!

**Comment by gperonato** [comment]
As a first implementation, I would
- consider all raster containing numerical values (Indeed there are some Hotmaps layers that look categorical but this is not completely clear from the metadata, we'll have to address this issue later).
- create a diverging color scale (e.g. blue-yellow-red gradient)
- read the min-max values with a library (e.g. gdal or rasterio)
- associate the min-max to the color scale (i.e., with a continuous scale, without predefined intervals).
- the unit should be the returned by the latest version of the query ("units" field of the GeoJSON).
@dianevg do you agree?
@melhk is this feasible? For example for dataset1, fid "gh_0_01_band1_3035.tif". The min-max range should be 13.9-284.6.
Let me know if something is not clear.

**Comment by dianevg** [comment]
Hello Giuseppe and Mélanie,

Yes, what Giuseppe is proposing is what we discussed last time. Conceptually, it is really similar to the process used for vector file. So, for raster with numerical value, we find the minimum and maximum value of the raster and creating a colormap. The unit is available from the DB in "data" table if I am not mistaken. The variable is the one shown on the front-end. If there are more than one variable in the raster , it should be selected in the configuration file.

The difficulties will indeed be to know if the raster is categorical or numerical in nature, this might be something to add in the metadata. I did not know that we had categorical data. @gperonato would it possible? 

For categorical data, the usual thing is to make a list of all unique value and to assign a color to each value from a color map (if you have ten value, you write a small script to chose ten colors from the colormap).

Another point: I am not sure why the maximum and minimum value is stored in the configuration file? Could you not calculate it ? If the data change, it seems logical that the maximum and minimum would change automatically.

For the caption is depends on what you use to show the caption in the front-end. I would try to see what is the most practical fro you.

**Comment by gperonato** [comment]
> The difficulties will indeed be to know if the raster is categorical or numerical in nature, this might be something to add in the metadata. I did not know that we had categorical data. @gperonato would it possible?

Yes, I checked again and unfortunately, there are some layers from the Hotmaps datasets that should be probably visualized as categorical. E.g. the climate_zones of dataset 31 (0 for warmer climate, 1 for average and 2 for colder climate). 

> For categorical data, the usual thing is to make a list of all unique value and to assign a color to each value from a color map (if you have ten value, you write a small script to chose ten colors from the colormap).

I will add some metadata with for this dataset in the database (e.g. `{0:  "warmer climate", 1: "average", 2: "colder climate"}`). I guess the color should be then attributed directly by the front end ans you mentioned.

**Comment by melhk** [comment]
@dianevg Yes, we can calculate what we calculated manually and stored in our "fake database". But do you want to download the whole dataset then parse it and therefore wait sometimes for minutes each time you click on a layer to display? 
Moreover, where will we look for indications such as the variable used to calculate the legend if we don't use our "fake database"?

**Comment by melhk** [comment]
@gperonato I would prefer that you give me a file containing all the information I need for all the layers used for the September demonstration, and I will do something similar I did for the vector layers.
What you suggested is not feasible for the future development of the website (see my answer to Diane above). Remember we cannot download and store the entire database in the back end!

**Comment by Kanma** [comment]
Not an issue anymore in the current version of the web app.
