### ISSUE TITLE
"Scale direction" of the legends 

### ISSUE THREAD

**Issue by melhk** [enermaps/enermaps#277]
This raster appears to have its legend inverted from the colors in the image. Is this correct? Is this the case for all the other rasters or only a few? How can we know this scale direction (black to white or inverted white to black)?

![1](https://user-images.githubusercontent.com/11057275/129580666-039f7e88-c648-48a4-b16d-80308d474124.PNG)

**Comment by gperonato** [comment]
There is no "direction" in the legend, it really depends on the color scale you use.
Here the map is confusing because the high-density spots are white but there are also many areas without data (e.g. non-urbanized areas) that are also white.
I would suggest changing the color scale to real colors (e.g. blue-to-yellow-to-red, instead of black-to-white).

**Comment by melhk** [comment]
Can you explain to me how to do this correctly please?

**Comment by gperonato** [comment]
There is no right or wrong here.
You might just want to change the default colors. Any [sequential colormap ](https://matplotlib.org/stable/tutorials/colors/colormaps.html) other than `greys` would be ok for now.
Later on, we might let the user choose specific vmin-vmax or change the color scale.

**Comment by melhk** [comment]
Your link is pointing on a page explaining how do colormaps (color palettes) work in matplotlib... not how to change the inner colormap of a raster.....
My question was, have you already done this and can you show me how?

**Comment by gperonato** [comment]
There is no colormap associated with the raster file. What you see is the default visualization from the tool you are using. I haven't used Mapnik before, so I don't think I can be of much help.

**Comment by gperonato** [comment]
But if you think I can help, feel free to contact me in private.

**Comment by dianevg** [comment]
Hello Mélanie,

Here is what I would do if I would code this project (which I don't and I don't know the code in detail, so don't take my word for it) : 
- It seems to me there are different choice available to solve this problem. An important choice is to know if we manage the color of the raster when we show it or when we download it from the database. 
- As we would like to get a responsive front-end and that we do not need to change the color of the raster after having showing it, I would manage the color issue at the "downloading" time. (Also I avoid mapnik as my next meeting is in 5 minutes).
- As Gdal is in the requirement.txt already, we can use Gdal. There are different utilities to control color in gdal, but I like gdaldem with color-relief (https://gdal.org/programs/gdaldem.html -> use with the Python format here)
- in the script enermaps_server.py, add the gdal transformation at the line 120 (if I get your code right). Something like gdal.DEMProcessing(r'export.tif', r'input.tif', **kwargs).
-  Save your updated raster with less data but with the color you want. 
- Enjoy!

**Comment by melhk** [comment]
Hello Diane, thank you for your answer!
Unfortunately, the solution "at the downloading time" is not a good one, because all the downloading that we do at the is a backup solution for the September demonstration, and it will have to be removed later in the project.
Anyway, what I was asking was not how to code, but where to find the necessary information to make the legends correctly. For now, I'll just work with the config file.

**Comment by Kanma** [comment]
Not an issue anymore in the current version of the web app.
