### ISSUE TITLE
Data on relative humidity illogical

### ISSUE THREAD

**Issue by dianevg** [enermaps/enermaps#299]
The data shown the layer representing the relative humidity is above 100% while it should stays  between 0 and 100%.

**Comment by gperonato** [comment]
There is a problem with `gdal_warp` affecting all rasters from Copernicus.
Here's the plan:

- [x] correct code involving `gdal_warp` see #313 
- [x] running a script correcting files for dataset 15 using `offset` and `scale` values from the DB
- [x] running a script correcting files for dataset 20 using `offset` and `scale` values from the DB

**Comment by gperonato** [comment]
> The data shown the layer representing the relative humidity is above 100% while it should stays between 0 and 100%.

Even after converting the files, some percentage values are above 100%.
For example, https://lab.idiap.ch/enermaps/raster/20/2019-01-01_r_band1_3035.tif has a maximum of 113%. The original file from Copernicus seems to have the same value.

**Comment by dianevg** [comment]
Hello Giuseppe,
It is possible to have value above 100% in relative humidity. It indicates super staturation and air which are unstable but which do not condensate directly as it is in high altitude with low impurities (in other word, it should rain very soon there) . It might also be difference in where the measurement are done or uncertainties. Maximum value of 113% would not worry me as long it is not a common situation. But value of 1000% is wrong.

**Comment by gperonato** [comment]
> Hello Giuseppe,
> It is possible to have value above 100% in relative humidity. It indicates super staturation and air which are unstable but which do not condensate directly as it is in high altitude with low impurities (in other word, it should rain very soon there) . It might also be difference in where the measurement are done or uncertainties. Maximum value of 113% would not worry me as long it is not a common situation. But value of 1000% is wrong.

Ok, thanks for the explanation. We should be fine then. The previous values were definitely not scaled correctly, so not expressing an actual percentage.
