### ISSUE TITLE
.cdsapirc not found in build context

### ISSUE THREAD

**Issue by MaxiReglisse** [enermaps/enermaps#334]
Hello,

the command "docker-compose --file docker-compose-db.yml up --build" fails with the following error:

    Step 8/16 : COPY .cdsapirc /root/.cdsapirc
    COPY failed: file not found in build context or excluded by .dockerignore: stat .cdsapirc: file does not exist
    ERROR: Service 'data-integration' failed to build

thank you in advance for your help

Ernest.

**Comment by gperonato** [comment]
Sorry for the late reply.
The `.cdsapirc` file contains the API key associated with one's personal account in Copernicus Climate Store. As such it is a private file and cannot be included in this public repository.
You can find more information on how to create this file here:
https://cds.climate.copernicus.eu/api-how-to
This file should be then located in `/data-integration/.cdsapirc` to be used within the Docker service
