### ISSUE TITLE
Group layer by topic to find them more easily

### ISSUE THREAD

**Issue by dianevg** [enermaps/enermaps#364]
step 1 : Add a column in the database with the subject

**Comment by Kanma** [comment]
This is now supported in the UI:

<img width="248" alt="Screenshot 2021-10-20 at 09 31 56" src="https://user-images.githubusercontent.com/159619/138047924-cce1bbb5-e044-4e31-b094-ef125d4df622.png">

The only thing is that currently the datasets are assigned to groups going from ```A``` to ```F```. So we need to come up with actual names for those groups, and store that information somewhere, either in the database or hard-coded at the web API level (which would be less flexible in case of a new group in the future).
