### ISSUE TITLE
API crashes

### ISSUE THREAD

**Issue by knackbord** [enermaps/enermaps#37]
The API is crashing
api_1       | app.models.geofile.SaveException: File is an invalid zip file.
api_1       | [2020-11-13 14:09:35 +0100] [7] [INFO] Worker exiting (pid: 7)
api_1       | Ensure we have the initial dataset
api_1       | Fetching nuts0.zip
api_1       | [2020-11-13 14:09:35 +0100] [1] [INFO] Shutting down: Master
api_1       | [2020-11-13 14:09:35 +0100] [1] [INFO] Reason: Worker failed to boot.
enermaps2_api_1 exited with code 3

Any ideas why?

**Comment by knackbord** [comment]
api_1       | [2020-11-13 14:11:28 +0100] [1] [INFO] Starting gunicorn 20.0.4
api_1       | [2020-11-13 14:11:28 +0100] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
api_1       | [2020-11-13 14:11:28 +0100] [1] [INFO] Using worker: sync
api_1       | [2020-11-13 14:11:28 +0100] [7] [INFO] Booting worker with pid: 7
api_1       | [2020-11-13 14:11:29 +0100] [7] [ERROR] Exception in worker process
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/lib/python3.8/zipfile.py", line 1332, in _RealGetContents
api_1       |     endrec = _EndRecData(fp)
api_1       |   File "/usr/lib/python3.8/zipfile.py", line 264, in _EndRecData
api_1       |     fpin.seek(0, 2)
api_1       | io.UnsupportedOperation: seek
api_1       |
api_1       | During handling of the above exception, another exception occurred:
api_1       |
api_1       | Traceback (most recent call last):
api_1       |   File "/api/app/models/geofile.py", line 206, in save
api_1       |     zip_ref = zipfile.ZipFile(file_upload, "r")
api_1       |   File "/usr/lib/python3.8/zipfile.py", line 1269, in __init__
api_1       |     self._RealGetContents()
api_1       |   File "/usr/lib/python3.8/zipfile.py", line 1334, in _RealGetContents
api_1       |     raise BadZipFile("File is not a zip file")
api_1       | zipfile.BadZipFile: File is not a zip file
api_1       |
api_1       | During handling of the above exception, another exception occurred:
api_1       |
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 583, in spawn_worker
api_1       |     worker.init_process()
api_1       |   File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 119, in init_process
api_1       |     self.load_wsgi()
api_1       |   File "/usr/lib/python3/dist-packages/gunicorn/workers/base.py", line 144, in load_wsgi
api_1       |     self.wsgi = self.app.wsgi()
api_1       |   File "/usr/lib/python3/dist-packages/gunicorn/app/base.py", line 67, in wsgi
api_1       |     self.callable = self.load()
api_1       |   File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 49, in load
api_1       |     return self.load_wsgiapp()
api_1       |   File "/usr/lib/python3/dist-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
api_1       |     return util.import_app(self.app_uri)
api_1       |   File "/usr/lib/python3/dist-packages/gunicorn/util.py", line 383, in import_app
api_1       |     mod = importlib.import_module(module)
api_1       |   File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
api_1       |     return _bootstrap._gcd_import(name[level:], package, level)
api_1       |   File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
api_1       |   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
api_1       |   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
api_1       |   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
api_1       |   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
api_1       |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
api_1       |   File "/api/wsgi.py", line 5, in <module>
api_1       |     app = create_app()
api_1       |   File "/api/app/__init__.py", line 70, in create_app
api_1       |     init_dataset()
api_1       |   File "/api/app/__init__.py", line 35, in init_dataset
api_1       |     create(file_upload)
api_1       |   File "/api/app/models/geofile.py", line 47, in create
api_1       |     return VectorLayer.save(file_upload)
api_1       |   File "/api/app/models/geofile.py", line 208, in save
api_1       |     raise SaveException("File is an invalid zip file.")
api_1       | app.models.geofile.SaveException: File is an invalid zip file.
api_1       | [2020-11-13 14:11:29 +0100] [7] [INFO] Worker exiting (pid: 7)
api_1       | Ensure we have the initial dataset
api_1       | Fetching nuts0.zip
api_1       | [2020-11-13 14:11:29 +0100] [1] [INFO] Shutting down: Master
api_1       | [2020-11-13 14:11:29 +0100] [1] [INFO] Reason: Worker failed to boot.

**Comment by gcmalloc** [comment]
Looks like a mix between uncomplete stream in request and the version pinning of the request library. 
See the linked PR for the fix.

**Comment by gcmalloc** [comment]
Fixed now, reopen the issue if you encounter the same issue again.
