### ISSUE TITLE
PVGIS layer shows no data for half of EU: is that legend or selection problem?

### ISSUE THREAD

**Issue by dianevg** [enermaps/enermaps#371]

**Comment by gperonato** [comment]
I checked the raster that is displayed in the frontend.
`docker cp enermaps_api_1:"/geodb/raster/01_PVGIS: Solar Radiation Data.tiff/raster.tiff" PVGIS.tiff`
and it seems ok when opened in QGIS.
<img width="539" alt="image" src="https://user-images.githubusercontent.com/9164610/137888847-6431eb5d-92a8-44a7-8bea-f7627dc63573.png">

Also, the min and max values seem correctly set in the (legacy) `enermaps/api/app/data_integration/data_config.py` file.

@Kanma Any idea on this?

**Comment by Kanma** [comment]
The legend starts at 12W/m^2, so I guess this might be the problem (I'm displaying January here, in February there is already mode data, but not everywhere yet).

<img width="382" alt="Screenshot 2021-10-19 at 14 39 46" src="https://user-images.githubusercontent.com/159619/137910980-960720fa-b96c-442e-8513-dc9495e72b23.png">

**Comment by gperonato** [comment]
I also thought that this was the problem. But the raster currently in production actually has a minimum at 13.90, which corresponds to the minimum of the legend.
