### ISSUE TITLE
Test the api-broker-cm interaction

### ISSUE THREAD

**Issue by gcmalloc** [enermaps/enermaps#84]
Test the set of service api+broker+cm in an integration test. 

Scaffold for this is in https://github.com/enermaps/enermaps2/blob/master/api/app/endpoints/test_calculation_module.py.

**Comment by gcmalloc** [comment]
first test for checking that the cm registration is working correctly is merged, will add some more test about the call to a cm.

**Comment by dianevg** [comment]
Add  a test for the full integration for one CM including selection ?)
